apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    run: mysql-pod
spec:
  containers:
  - image: mysql
    name: mysql-pod
    envFrom:
    - configMapRef:
       name: db-config
    - secretRef:
       name: db-secret
  tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
